{
    "name": "Project Work Items From Sale Order",
    "version": "17.0.1.0.0",
    "depends": [
        "project",
        "sale",
        "contract_management",
        "custom_sale_project",
        "proposal_sheet",
        "cost_estimate",
        "custom_project_expense",
        "custom_project_role",
        "web",
        "mail",
        # "your_contract_module_name",  # <- đổi thành tên module chứa model contract.management của bạn
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/project_work_rules.xml",
        "security/rules.xml",
        # "views/manager_work_item_dashboard_action.xml",
        'wizard/project_report_assign_multi_wizard_views.xml',
        "views/project_work_dashboard_action.xml",
        "views/project_project_custom_views.xml",
        "views/my_weekly_report_assignment_views.xml",
        "views/manager_work_item_views.xml",
        'views/project_rename_menu.xml',
        'views/project_work_item_views.xml',
    ],
        "assets": {
        "web.assets_backend": [
            "project_work_from_so/static/src/work_item_dashboard/work_item_dashboard.xml",
            "project_work_from_so/static/src/work_item_dashboard/work_item_dashboard.js",
            "project_work_from_so/static/src/work_item_dashboard/work_item_dashboard.scss",
            "project_work_from_so/static/src/project_dashboard/project_dashboard.xml",
            "project_work_from_so/static/src/project_dashboard/project_dashboard.js",
            "project_work_from_so/static/src/project_dashboard/project_dashboard.scss",
            'project_work_from_so/static/src/form/project_work_project_form_owl.js',
            'project_work_from_so/static/src/form/project_work_project_form_owl.xml',
            'project_work_from_so/static/src/form/project_work_project_form_owl.scss',
            "project_work_from_so/static/src/js/my_assignment_project_list.js",
            'project_work_from_so/static/src/js/my_assignment_report.js',
            'project_work_from_so/static/src/js/cost_estimate_standard_screen.js',
            'project_work_from_so/static/src/js/project_expense_standard_screen.js',
            'project_work_from_so/static/src/js/project_invoice_standard_screen.js',
            'project_work_from_so/static/src/js/project_task_standard_screen.js',
            'project_work_from_so/static/src/xml/my_assignment_report.xml',
            'project_work_from_so/static/src/xml/cost_estimate_standard_screen.xml',
            'project_work_from_so/static/src/xml/project_expense_standard_screen.xml',
            'project_work_from_so/static/src/xml/project_invoice_standard_screen.xml',
            'project_work_from_so/static/src/xml/project_task_standard_screen.xml',
            'project_work_from_so/static/src/scss/my_assignment_report.scss',
        ],
    },
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
