# -*- coding: utf-8 -*-
# Part of Creyox Technologies
{
    "name": "Material Purchase Requisitions | Material Requisitions By Employee | Material Requisitions By Users | Material Request in Odoo | Material Requisition",
    "author": "Creyox Technologies",
    "website": "https://www.creyox.com",
    "support": "support@creyox.com",
    "category": "Purchase",
    "summary": """
    Material Requisition,
    Material Request in Odoo,
    Product/Material Purchase Requisitions and Internal Picking Requisitions by Employees / Users,
    Maternal Requisition Request by Employee/User Odoo App,
    Material Requisition Request in odoo,
    Purchase Material Requisition Request in odoo,
    Purchase Material Requisition Request by Employee in odoo,
    Purchase Material Requisition Request by User in odoo,
    Material Requisition Request by Employee in odoo,
    Material Requisition Request by User in odoo,
    Material Requisitions By Employee,
    Material Requisitions By Employee in odoo,
    Material Requisitions By Users,
    Material Requisitions By Users in odoo,
""",
    "license": "LGPL-3",
    "version": "17.0",
    "description": """

    This module helps to manage Material Purchase requisition for all Employees and User by Purchase Order or Internal Transfer,
    Material Requisition,
    Material Request in Odoo,
    Product/Material Purchase Requisitions and Internal Picking Requisitions by Employees / Users,
    Maternal Requisition Request by Employee/User Odoo App,
    Material Requisition Request in odoo,
    Purchase Material Requisition Request in odoo,
    Purchase Material Requisition Request by Employee in odoo,
    Purchase Material Requisition Request by User in odoo,
    Material Requisition Request by Employee in odoo,
    Material Requisition Request by User in odoo
""",
    "depends": ["base", "hr", "stock", "purchase"],
    "data": [
        "security/ir.model.access.csv",
        "security/res_groups.xml",
        "data/ir_sequence_data.xml",
        "views/employee.xml",
        "views/department.xml",
        "views/purchase_requisition.xml",
        "views/picking_count.xml",
        "views/purchase_count.xml",
        "report/purchase_request_report.xml",
        "report/purchase_request_template.xml",
        "wizard/rejected.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "images": ["static/description/banner.png"],
    "price": 0,
    "currency": "USD",
}
