version: "3.1"

services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    command: >
      /bin/bash -c "
      pip install --no-cache-dir Pillow openpyxl xlrd xlsxwriter boto3 &&
      exec /usr/bin/odoo --config /etc/odoo/odoo.conf
      "
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 604800
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
