version: "3.1"
services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # ⚡ đổi thành email bạn muốn
      PGADMIN_DEFAULT_PASSWORD: admin123 # ⚡ đổi thành password bạn muốn
    ports:
      - "5050:80" # Truy cập pgadmin qua http://localhost:5050
    depends_on:
      - db
volumes:
  odoo-web-data:
  odoo-db-data:
