from . import proposal_sheet_inherit
from . import purchase_order_inherit
from . import project_task_inherit
from . import account_payment_request
from . import purchase_advance_payment_wizard
from . import stock_picking_inherit
from . import supplier_invoice
from . import project_task_optional_stages
from . import purchase_create_supplier_invoice_wizard
