{
    "name": "Supplier Debt Management",
    "version": "1.0",
    "author": "Your Company",
    "category": "Accounting",
    "depends": ["base", "project", "contacts", "custom_account_payment_request", "web", "account"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/supplier_contract_views.xml",
        "views/supplier_settlement_views.xml",
        "views/supplier_invoice_views.xml",
        'views/supplier_invoice_summary_views.xml',
        # 'views/res_partner_view_supplier_extra.xml',
        "views/account_payment_request_views.xml",
        'views/supplier_views.xml',
        "report/report_supplier_summary.xml",
        "report/report_supplier_summary_real.xml",
        "report/report_supplier_detail.xml",
        "report/report_supplier_invoice.xml",
        "report/supplier_invoice_summary_report.xml",
        "wizard/wizard_views.xml",
        "wizard/supplier_invoice_wizard.xml",
        "views/supplier_debt_owl_report_action.xml",
            'views/vendor_debt_share_templates.xml',
    ],
    "assets": {
    "web.assets_backend": [
        "vendor_debt_management/static/src/js/supplier_debt_real_report.js",
        "vendor_debt_management/static/src/xml/supplier_debt_real_report.xml",
        "vendor_debt_management/static/src/scss/supplier_debt_real_report.scss",
        "vendor_debt_management/static/src/js/supplier_debt_owl_report.js",
        "vendor_debt_management/static/src/xml/supplier_debt_owl_report.xml",
        "vendor_debt_management/static/src/scss/supplier_debt_owl_report.scss",
    ],
},
    "installable": True,
    "application": True,
}
